parameters:
#    ito_model.example.class: ItoSoftware\Base\ModelBundle\Example

services:
#    ito_model.example:
#        class: %ito_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    