parameters:
#    ito_user.example.class: ItoSoftware\Base\UserBundle\Example

services:
#    ito_user.example:
#        class: %ito_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

            
    authentication_admin_handler:
        class: ItoSoftware\Base\UserBundle\Handler\AuthenticationHandler
        public: false
        arguments:  ['@router', '@translator', '@service_container']
    
    logout_admin_handler:
        class: ItoSoftware\Base\UserBundle\Handler\LogoutHandler
        arguments:  ['@router'] 
          
          
    ito_admin.admin.ito_user:
        class: ItoSoftware\Base\AdminBundle\Admin\ItoUserAdmin
        arguments: [~, ItoSoftware\Base\ModelBundle\Entity\User, ItoAdminBundle:ItoUserAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: User, label: User}
            
    ito_admin.admin.ito_group:
        class: ItoSoftware\Base\AdminBundle\Admin\ItoGroupAdmin
        arguments: [~, ItoSoftware\Base\ModelBundle\Entity\Group, ItoAdminBundle:ItoGroupAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: User, label: Group}