imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: custom/sonata_config.yml }
    - { resource: custom/sensio_extra.yml }
    - { resource: custom/fos_rest.yml }
    - { resource: services.yml }
    - { resource: "@ItoUserBundle/Resources/config/services.yml" }
    - { resource: "@ItoUserBundle/Resources/config/config.yml" }
    - { resource: "@WebAppAdminBundle/Resources/config/admin.yml" }
    
fos_user:
    user_class: ItoSoftware\Base\ModelBundle\Entity\User
    group:
        group_class: ItoSoftware\Base\ModelBundle\Entity\Group

framework:
    http_method_override: true
    #esi:             ~
    translator:      { fallback: "es" }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        project_name: 'Plataforma Enlace'
        web_path: %kernel.root_dir%/../web  
    form:
        resources:
            - 'WebAppFrontendBundle:Form:fields.html.twig'
            - LexikFormFilterBundle:Form:form_div_layout.html.twig

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            string_functions:
                unaccent: WebApp\FrontendBundle\Filter\Unaccent

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    
parameters:
    project_name: 'Plataforma Enlace' 

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: WebAppFrontendBundle:Pagination:sliding.html.twig # plantilla utilizada en la paginación
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template