web_app_api:
    resource: "@WebAppApiBundle/Resources/config/routing.yml"
    prefix:   /api
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

web_app_frontend:
    resource: "@WebAppFrontendBundle/Resources/config/routing.yml"
    prefix:   /

web_app_admin:
    resource: "@WebAppAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

redirect_admin:
    pattern:  /admin
    defaults: { _controller: WebAppAdminBundle:Default:redirectAdmin }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change_password
    
#fos_user_profile_show:
#    pattern:  /user/password-recovery
#    defaults: { _controller: ItoUserBundle:Default:passwordRecovery }

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin/
  
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/
  
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin