parameters:
#    web_app_api.example.class: WebApp\ApiBundle\Example

services:
#    web_app_api.example:
#        class: %web_app_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
