fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        formats:
            json: true
    format_listener:
        rules:
            prefer_extension: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json