parameters:
#    web_app_admin.example.class: WebApp\AdminBundle\Example

services:
#    web_app_admin.example:
#        class: %web_app_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
