<?php

namespace ItoSoftware\Base\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AulaFotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AulaFotoRepository extends EntityRepository
{
}
