<?php

namespace ItoSoftware\Base\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AulaMusicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AulaMusicalRepository extends EntityRepository
{
}
