<?php

namespace Proxies\__CG__\ItoSoftware\Base\ModelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AulaMusical extends \ItoSoftware\Base\ModelBundle\Entity\AulaMusical implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'id', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'titulo', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'municipio', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'descripcion', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'componente', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'capacitaciones', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'detalle', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'lugar', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'slug', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'comentarios_aula', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'aula_fotos');
        }

        return array('__isInitialized__', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'id', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'titulo', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'municipio', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'descripcion', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'componente', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'capacitaciones', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'detalle', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'lugar', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'slug', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'comentarios_aula', '' . "\0" . 'ItoSoftware\\Base\\ModelBundle\\Entity\\AulaMusical' . "\0" . 'aula_fotos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AulaMusical $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(\ItoSoftware\Base\ModelBundle\Entity\Municipio $municipio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', array($municipio));

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', array());

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setComponente($componente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComponente', array($componente));

        return parent::setComponente($componente);
    }

    /**
     * {@inheritDoc}
     */
    public function getComponente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponente', array());

        return parent::getComponente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacitaciones($capacitaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacitaciones', array($capacitaciones));

        return parent::setCapacitaciones($capacitaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacitaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacitaciones', array());

        return parent::getCapacitaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalle($detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalle', array($detalle));

        return parent::setDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalle', array());

        return parent::getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugar($lugar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugar', array($lugar));

        return parent::setLugar($lugar);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugar', array());

        return parent::getLugar();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function addComentariosAula(\ItoSoftware\Base\ModelBundle\Entity\ComentarioAula $comentariosAula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComentariosAula', array($comentariosAula));

        return parent::addComentariosAula($comentariosAula);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComentariosAula(\ItoSoftware\Base\ModelBundle\Entity\ComentarioAula $comentariosAula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComentariosAula', array($comentariosAula));

        return parent::removeComentariosAula($comentariosAula);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentariosAula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentariosAula', array());

        return parent::getComentariosAula();
    }

    /**
     * {@inheritDoc}
     */
    public function addAulaFoto(\ItoSoftware\Base\ModelBundle\Entity\AulaFoto $aulaFotos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAulaFoto', array($aulaFotos));

        return parent::addAulaFoto($aulaFotos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAulaFotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAulaFotos', array());

        return parent::getAulaFotos();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlugFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlugFields', array());

        return parent::getSlugFields();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
