parameters:
#    web_app_modelo.example.class: WebApp\ModeloBundle\Example

services:
#    web_app_modelo.example:
#        class: %web_app_modelo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
